name: URL File Downloader

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true
        type: string
      filename:
        description: 'Custom filename for the downloaded file (optional)'
        required: false
        type: string

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract filename from URL or use custom name
        id: filename
        run: |
          if [ -n "${{ github.event.inputs.filename }}" ]; then
            FILENAME="${{ github.event.inputs.filename }}"
          else
            FILENAME=$(basename "${{ github.event.inputs.file_url }}")
            # If basename doesn't give us a filename with extension, use a default
            if [ -z "$FILENAME" ] || [ "$FILENAME" = "/" ]; then
              FILENAME="downloaded_file"
            fi
          fi
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "Downloading as: $FILENAME"

      - name: Download file from URL
        run: |
          echo "Downloading from: ${{ github.event.inputs.file_url }}"
          curl -L -f "${{ github.event.inputs.file_url }}" -o "${{ env.FILENAME }}"
          echo "File downloaded successfully"
          ls -la "${{ env.FILENAME }}"

      - name: Upload downloaded file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file-${{ env.FILENAME }}
          path: ${{ env.FILENAME }}
          retention-days: 1
