name: Docker Image Puller

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker image to pull (format: image:tag)'
        required: true
        type: string

jobs:
  pull-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker image
        run: docker pull ${{ github.event.inputs.docker_image }}
        
      - name: Extract image name for artifact
        id: image-name
        run: |
          IMAGE_NAME=$(echo "${{ github.event.inputs.docker_image }}" | sed 's/[\/:]/-/g')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Save Docker image as tar
        run: docker save ${{ github.event.inputs.docker_image }} -o ${{ env.IMAGE_NAME }}.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-${{ env.IMAGE_NAME }}
          path: ${{ env.IMAGE_NAME }}.tar
          retention-days: 1
